# -------------------------------------------------------------------------------------
#  --------------------------- Startship Prompt --------------------------------------- 
# -------------------------------------------------------------------------------------

"$schema" = 'https://starship.rs/config-schema.json'

# Insert new line 
add_newline = false

# Using Nerd Font symbols with some curved arrow tools
# https://emojicombos.com/curved-arrow
# 
#  
# 󰤃 ╰ ╭

# My custom font
format = '''
[ ╭ ](bold white)$username $directory $git_branch $git_status $fill $right_promt
[ ╰ ](bold white)
'''

right_format = "$os at $time on $shell"

# Characters Configurations
# --------------------------------------------------------

[username]
format = " [$user]($style)"
disabled = false
show_always = true
aliases = { "tarunbhandari" = "taruu" }

[directory]
format = "at [  $path]($style)"
truncation_length = 3
truncation_symbol = "../"
read_only = " 󰌾"

[directory.substitutions]
"~" = "󱂵 Home"
"dotfiles" = "󱁿  dotfiles"
