# -------------------------------------------------------------------------------------
#  --------------------------- Startship Prompt --------------------------------------- 
# -------------------------------------------------------------------------------------

"$schema" = 'https://starship.rs/config-schema.json'

# Insert new line 
add_newline = false

# Using Nerd Font symbols with some curved arrow tools
# https://emojicombos.com/curved-arrow
# 
#  
# 󰤃 ╰ ╭

# My custom font
format = '''
[ ╭ ](bold white)$username $directory $git_branch $git_status
[ ╰ ](bold white)
'''

right_format = "$os at $time on $shell"

# Characters Configurations
# --------------------------------------------------------

[username]
format = " [$user]($style)"
disabled = false
show_always = true
aliases = { "tarunbhandari" = "taruu" }

[directory]
format = "at [  $path]($style)"
truncation_length = 3
truncation_symbol = "../"
read_only = " 󰌾"

[directory.substitutions]
"~" = "󱂵 Home"
"dotfiles" = "󱁿  dotfiles"

[git_branch]
symbol = "󰘬"
format = "on [$symbol $branch(:$remote_branch)]($style)"
truncation_length = 4
truncation_symbol = ""
ignore_branches = []

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
up_to_date = ""

#[fill]
#symbol = ''
#style = "bold white"

[os.symbols]
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
Garuda = "󰛓 "
Kali = " "
Linux = " "
Macos = " "
NixOS = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[os]
format = "on [($name $symbol )]($style)"
disabled = false
