# -------------------------------------------------------------------------------------
#  --------------------------- Startship Prompt --------------------------------------- 
# -------------------------------------------------------------------------------------

"$schema" = 'https://starship.rs/config-schema.json'

# Insert new line 
add_newline = false

# Using Nerd Font symbols with some curved arrow tools
# https://emojicombos.com/curved-arrow
# 
#  
# 󰤃 ╰ ╭

# My custom font
format = '''
[ ╭ ](bold white)$user $directory in $git_branch$git_status
[ ╰ ](bold white) 
'''

right_format = "[](bold white)$os at $time on $shell"

